---
- name: "Set the ssh key with the new user"
  hosts: all
  remote_user: root
  roles:
    - setting

- name: "Installation of the mysql server"
  hosts: dbserver
  remote_user: fcastelain
  become: true
  vars:
    ansible_port: "14159"
  vars_files:
    - mysql/vars/main.yml
  roles:
    - { role: mysql }
